version: '3'
services:
  db:
    build: ./data
    restart: always
    env_file:
      - ./back-end/.env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
  back-end:
    build: ./back-end
    restart: always
    depends_on:
      - db
    volumes:
      - ./back-end/src:/usr/src/app/src
      - ./back-end/uploads:/usr/src/app/uploads
      - ./back-end/prisma:/usr/src/app/prisma
    env_file:
      - ./back-end/.env
  front-end:
    build: ./front-end
    restart: always
    env_file:
      - ./front-end/.env
    depends_on:
      - back-end
    volumes:
      - ./front-end/src:/usr/src/app/src
  nginx :
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - back-end