version: '3'
services:
  db:
    build: ./data
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  back-end:
    build: ./back-end
    restart: always
    depends_on:
      - db
    volumes:
      - ./back-end/src:/usr/src/app/src
    ports:
      - "3001:3001"
      - "5555:5555"
  front-end:
    build: ./front-end
    restart: always
    depends_on:
      - back-end
    volumes:
      - ./front-end/src:/usr/src/app/src
    ports:
      - "3000:3000"