-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "CreationTime" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "Player2IsWinner" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "player1IsWinner" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "isDraw" SET DEFAULT false;
